### PR TITLE
feat/seedData and dotEnv

### PR DESCRIPTION
**Pull request by nathanielbelen**
- added dotenv and refactored code to use .env file
- ignored env
- added seed data for products, reviews, and questions

### CODE REVIEW

**Comment by nathanielbelen** [comment]
[Add and configure dotenv](https://trello.com/c/b92ikkSW/59-add-and-configure-dotenv)

**Comment by nathanielbelen** [comment]
[Get API Test Data](https://trello.com/c/RtaTTAFq/30-get-api-test-data)

**Comment by kimberlysiu** [comment]
Dot env module missing.

**Comment by kimberlysiu** [comment]
Looks good @nathanielbelen

**Pull request merged**
